### ISSUE TITLE
The trained network.pth file.

### ISSUE THREAD

**Issue by AhmedKhaled945** [lood339/SCCvSD#10]
Hello, wanted to ask if you can attach the network.pth file from the siamese training, as my training is not working, giving bad features (Not equal to the extracted features in the .mat files)

Thanks in advance. @lood339

**Comment by lood339** [comment]
Hi,
   Thanks for interesting in our work.
   The code was modified from a Matlab version about two years ago. If I remember correctly, I do not train the model using this python version because I do not have a GPU after graduated. 
   You can have a look this issue: https://github.com/lood339/SCCvSD/issues/6 to get some idea.
   Hope that helps.

**Comment by AhmedKhaled945** [comment]
Thanks a lot Dr.Chen for the prompt response.
